apiVersion: apps/v1
kind: Deployment
metadata:
  name: module3
  namespace: default
  labels:
    app: module3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: module3
  template:
    metadata:
      labels:
        app: module3
    spec:
      containers:
        - name: module3
          image: mojacr.azurecr.io/module3:latest   # ← ZMIEŃ NA SWÓJ OBRAZ
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # env:
          # - name: SPRING_PROFILES_ACTIVE
          #   value: "prod"