apiVersion: apps/v1
kind: Deployment
metadata:
  name: module3
  namespace: module3
  labels:
    app: module3
    app.kubernetes.io/name: module3
    app.kubernetes.io/part-of: bootroot

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  selector:
    matchLabels:
      app: module3

  template:
    metadata:
      labels:
        app: module3
        app.kubernetes.io/name: module3
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"

    spec:
      containers:
        - name: module3
          image: ghcr.io/jerzyoleksa/bootroot:main
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            requests:
              cpu: 150m
              memory: 300Mi
            limits:
              cpu: 600m
              memory: 600Mi

          # ====================== KAFKA CONFIG ======================
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"

            - name: SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET
              value: "earliest"

            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "module3-group"

            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          # =========================================================

          # Health checks